name: Deploy to Docker Hub

on:
  push:
    branches: ['develop']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout into this repository
        uses: actions/checkout@v3

      - name: use node version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
    #Test can go on here if present using npm

  Deploy_to_DockerHub:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/user-management-app:latest
